name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Version & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Changelog Content
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          awk '/^## /{if (p) exit; p=1} p' CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Read package version
        if: steps.changesets.outputs.hasChangesets == 'false'
        id: package
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Upload Extension Zip to GitHub Release
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: softprops/action-gh-release@v2
        with:
          files: release/release.zip
          body: ${{ env.RELEASE_NOTES }}
          tag_name: v${{ steps.package.outputs.version }}
          name: v${{ steps.package.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
