name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Version & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if release commit
        id: release_check
        run: |
          if [ "${{ steps.changesets.outputs.hasChangesets }}" = "false" ] && \
             [ "${{ github.event.head_commit.author.username }}" = "github-actions[bot]" ]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Get Changelog Content
        if: steps.release_check.outputs.is_release == 'true'
        run: |
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          awk '/^## /{if (p) exit; p=1} p' CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Read package version
        id: package
        if: steps.release_check.outputs.is_release == 'true'
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Upload Extension Zip to GitHub Release
        if: steps.release_check.outputs.is_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: release/release.zip
          body: ${{ env.RELEASE_NOTES }}
          tag_name: v${{ steps.package.outputs.version }}
          name: Over Tune v${{ steps.package.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
